services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    links:
      - postgres
    volumes:
      - ./backend:/app
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - backend-bd:/var/lib/postgresql/data
volumes:
  backend-bd:
