name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        scp -r -o StrictHostKeyChecking=no \
          ./backend ./frontend docker-compose.prod.yml \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/app

    - name: Deploy on server
      run: |
        ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "cd /home/${{ secrets.SERVER_USER }}/app && \
          docker-compose -f docker-compose.prod.yml down && \
          docker-compose -f docker-compose.prod.yml up -d --build"
