name: Despliegue con Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
